import { NextRequest, NextResponse } from 'next/server';
import { getSessionUser } from '@/lib/auth';
import { getSupabase } from '@/lib/supabase';
import { createPaymentUrl, createPaymentParams } from '@/lib/robokassa';

export async function POST(req: NextRequest) {
  const user = getSessionUser(req);
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = getSupabase();
  if (!supabase) {
    return NextResponse.json({ error: 'Service unavailable' }, { status: 503 });
  }

  const body = await req.json();
  const { packageId, locale } = body as { packageId: string; locale?: string };

  if (!packageId) {
    return NextResponse.json({ error: 'packageId is required' }, { status: 400 });
  }

  // Look up the package
  const { data: pkg, error: pkgErr } = await supabase
    .from('packages')
    .select('id, slug, generations, price_kzt, active')
    .eq('id', packageId)
    .single();

  if (pkgErr || !pkg) {
    return NextResponse.json({ error: 'Package not found' }, { status: 404 });
  }

  if (!pkg.active) {
    return NextResponse.json({ error: 'Package is not available' }, { status: 400 });
  }

  // Create payment row (inv_id is SERIAL, auto-generated by DB)
  const { data: payment, error: payErr } = await supabase
    .from('payments')
    .insert({
      user_id: user.userId,
      package_id: pkg.id,
      amount_kzt: pkg.price_kzt,
      status: 'pending',
    })
    .select('id, inv_id')
    .single();

  if (payErr || !payment) {
    return NextResponse.json({ error: 'Failed to create payment' }, { status: 500 });
  }

  const description = `Skezire: ${pkg.slug} (${pkg.generations} gen)`;
  const opts = { culture: locale, shpParams: { Shp_paymentId: payment.id } };

  const url = createPaymentUrl(payment.inv_id, pkg.price_kzt, description, opts);
  const params = createPaymentParams(payment.inv_id, pkg.price_kzt, description, opts);

  return NextResponse.json({ url, params });
}
